[platformio]
name = doom-esp32

[env:jc3248w535]
platform = espressif32
board = esp32-s3-devkitc1-n16r8
framework = espidf
build_flags =
    -DDOOM_ESP32
    -Isrc
    -Wno-unused-const-variable
monitor_speed = 115200

[env]
build_type = release
