[platformio]
name = doom-esp32
default_envs = jc3248w535

[env:jc3248w535]
platform = espressif32@6.12.0
board = esp32-s3-devkitc1-n16r8
framework = espidf
board_build.partitions = partitions_4mb.csv
build_flags =
    -DDOOM_ESP32
    -Isrc
    -Wno-unused-const-variable
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

[env]
build_type = release
