#ifndef PLATFORM_CONTROLS_H
#define PLATFORM_CONTROLS_H

// Native portrait layout shared by the LCD renderer and touch mapper.
#define PLATFORM_SCREEN_WIDTH 320
#define PLATFORM_SCREEN_HEIGHT 480
#define PLATFORM_GAME_HEIGHT 200
#define PLATFORM_STATUSBAR_HEIGHT 32
#define PLATFORM_STATUSBAR_TOP PLATFORM_GAME_HEIGHT
#define PLATFORM_CONTROLS_TOP (PLATFORM_STATUSBAR_TOP + PLATFORM_STATUSBAR_HEIGHT)
#define PLATFORM_CONTROLS_BOTTOM PLATFORM_SCREEN_HEIGHT
#define PLATFORM_LOWER_TOP PLATFORM_STATUSBAR_TOP

#define PLATFORM_JOYSTICK_RIGHT 190
#define PLATFORM_JOYSTICK_CENTER_X 95
#define PLATFORM_JOYSTICK_CENTER_Y 344
#define PLATFORM_JOYSTICK_DEAD_ZONE 24

#define PLATFORM_SOUND_CENTER_X 28
#define PLATFORM_SOUND_CENTER_Y 461
#define PLATFORM_SOUND_RADIUS 15
#define PLATFORM_SOUND_TOUCH_RADIUS 20

#define PLATFORM_BUTTONS_LEFT PLATFORM_JOYSTICK_RIGHT
#define PLATFORM_FIRE_BOTTOM 362
#define PLATFORM_USE_BOTTOM 440
#define PLATFORM_USE_STRAFE_SPLIT_X 262

// Shared bottom utility rail in the normal controls view.
#define PLATFORM_UTILITY_TOP 443
#define PLATFORM_SOUND_TOUCH_RIGHT 52
#define PLATFORM_WEAPONS_TOUCH_RIGHT 129
#define PLATFORM_CHEATS_TOUCH_RIGHT 210

// Modal weapon selector. Weapon indices deliberately match weapontype_t.
#define PLATFORM_WEAPON_COUNT 9
#define PLATFORM_WEAPON_CLOSE_LEFT 280
#define PLATFORM_WEAPON_CLOSE_TOP 238
#define PLATFORM_WEAPON_CLOSE_RIGHT 314
#define PLATFORM_WEAPON_CLOSE_BOTTOM 270
#define PLATFORM_WEAPON_GRID_LEFT 8
#define PLATFORM_WEAPON_GRID_TOP 274
#define PLATFORM_WEAPON_CELL_WIDTH 100
#define PLATFORM_WEAPON_CELL_HEIGHT 62
#define PLATFORM_WEAPON_CELL_GAP_X 4
#define PLATFORM_WEAPON_CELL_GAP_Y 4
#define PLATFORM_WEAPON_GRID_COLUMNS 3

#define PLATFORM_CHEAT_COUNT 6
#define PLATFORM_CHEAT_GRID_LEFT 8
#define PLATFORM_CHEAT_GRID_TOP 280
#define PLATFORM_CHEAT_CELL_WIDTH 100
#define PLATFORM_CHEAT_CELL_HEIGHT 86
#define PLATFORM_CHEAT_CELL_GAP_X 4
#define PLATFORM_CHEAT_CELL_GAP_Y 6
#define PLATFORM_CHEAT_GRID_COLUMNS 3

#endif
