#ifndef PLATFORM_CONTROLS_H
#define PLATFORM_CONTROLS_H

// Native portrait layout shared by the LCD renderer and touch mapper.
#define PLATFORM_SCREEN_WIDTH 320
#define PLATFORM_SCREEN_HEIGHT 480
#define PLATFORM_GAME_HEIGHT 200
#define PLATFORM_CONTROLS_TOP PLATFORM_GAME_HEIGHT

#define PLATFORM_JOYSTICK_RIGHT 190
#define PLATFORM_JOYSTICK_CENTER_X 95
#define PLATFORM_JOYSTICK_CENTER_Y 325
#define PLATFORM_JOYSTICK_DEAD_ZONE 24

#define PLATFORM_SOUND_CENTER_X 34
#define PLATFORM_SOUND_CENTER_Y 456
#define PLATFORM_SOUND_RADIUS 20
#define PLATFORM_SOUND_TOUCH_RADIUS 25

#define PLATFORM_BUTTONS_LEFT PLATFORM_JOYSTICK_RIGHT
#define PLATFORM_FIRE_BOTTOM 330
#define PLATFORM_USE_BOTTOM 432

#endif
